version: "3"

services:
  telegram-bot:
    image: ghcr.io/raffifu/money-tracker-bot
    restart: always
    depends_on:
      - bot_db
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      BOT_USERNAME: ${BOT_USERNAME}
      CREATOR_ID: ${CREATOR_ID}
      JDBC_DATABASE_URL: jdbc:mysql://bot_db:3306/${DB_NAME}
  bot_db:
    image: mariadb:10-focal
    restart: always
    container_name: ${DB_CONTAINER}
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      MARIADB_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
